title = "Custom Gitleaks Config"

[allowlist]

description = "Ignore generated/test files"

paths = [
  '''node_modules/''',
  '''build/''',
  '''dist/''',
  '''coverage/''',
  '''tests/''',
  '''__pycache__/''',
  '''package-lock.json''',
  '''yarn.lock'''
]

regexes = [
  '''fake-api-key''',
  '''dummy-secret''',
  '''test-password''',
  '''example-key'''
]